### ISSUE TITLE
Product planning feedback

### ISSUE THREAD

**Issue by Vennik** [HiVR/deliverables#10]
Hi,

The road map shouldn't be task based, but should consist of plans and goals.

I'm missing the motivation behind the prioritization in the product backlog.
And I didn't read anything about the stakeholder input.

Try using this to your advantage:
https://docs.google.com/spreadsheets/d/1S4MMFTxIK71wYVZB8eMcwko8v3yObnt64jSuw1pbMIc/pubhtml

**Comment by keohnoel** [comment]
Thanks for feedback, we've tried to implement it in our final version

**Comment by borisroman** [comment]
Closing, see PR #11
