### ISSUE TITLE
1 person for testing?

### ISSUE THREAD

**Issue by Vennik** [HiVR/deliverables#18]
Every person should write tests for his own code, you shouldn't let 1 person test all the code.

**Comment by AdriaanDeVos** [comment]
That is exactly what we written in our Definition of Done.

I guess this is about https://github.com/HiVR/deliverables/blob/master/sprint5/sprint_backlog.md
And task "Achieve 80% code coverage by writing missing tests"

This is specifically about the MISSING tests, every person will test his own features.

**Comment by Vennik** [comment]
So this means I can't take your backlog serious: https://github.com/HiVR/deliverables/blob/master/sprint5/sprint_backlog.md

**Comment by Vennik** [comment]
Probably better to let every person write the missing tests by what he build.

**Comment by AdriaanDeVos** [comment]
Good point, we will take it into account for the next sprint.
